server:
  port: 9090
  servlet.contextPath: /ecommerce
spring:
  data:
    mongodb.uri: mongodb+srv://EcommerceUser:EcommerceUser@cluster0-heq99.mongodb.net/test?retryWrites=true
    mongodb.database: test